# Generated by Django 5.1.2 on 2024-11-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinInstalacao',
            fields=[
                ('chekin_id', models.AutoField(primary_key=True, serialize=False)),
                ('estabelecimento', models.TextField(db_column='estabelecimento')),
            ],
            options={
                'db_table': '"br_addidas"."chekin"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"br_addidas"."store"',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='"br_addidas"."cadastro_usuario_cliente"',
        ),
    ]
