# Generated by Django 5.1.2 on 2024-11-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_usuario', '0002_checkininstalacao_store_alter_cliente_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinI',
            fields=[
                ('chekin_id', models.AutoField(primary_key=True, serialize=False)),
                ('estabelecimento', models.TextField(db_column='estabelecimento')),
                ('img', models.TextField(db_column='img')),
            ],
            options={
                'db_table': '"br_addidas"."chekin"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CheckinInstalacao',
        ),
    ]
