# Generated by Django 5.1.2 on 2024-11-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_usuario', '0005_model_db_campanha_delete_campanha'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_db_campanha_produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(db_column='nome_campanha')),
            ],
            options={
                'db_table': '"br_addidas"."produto"',
                'managed': False,
            },
        ),
    ]
