# Generated by Django 5.1.2 on 2024-11-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_usuario', '0008_model_db_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_db_cardapio',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('peca', models.CharField(db_column='peca')),
                ('Preco_uni', models.CharField(db_column='Preco uni')),
            ],
            options={
                'db_table': '"br_addidas"."cardapio_materiais"',
                'managed': False,
            },
        ),
    ]
