# Generated by Django 5.1.2 on 2024-12-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_usuario', '0010_model_db_checkini_upload_photo_chekin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_db_estabelecimento',
            fields=[
                ('id_estabelecimento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_estabelecimento', models.CharField(db_column='nome_estabelecimento')),
                ('cidade', models.CharField(db_column='cidade')),
                ('uf', models.CharField(db_column='uf')),
            ],
            options={
                'db_table': '"br_addidas"."estabelecimento"',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='upload_photo_chekin',
            options={'managed': False},
        ),
    ]
